### ISSUE TITLE
httparty ain't part of gem dependencies

### ISSUE THREAD

**Issue by mensfeld** [Luizin5/brwiki#1]
They trying to use this package, I get:

```
/app/vendor/bundle/ruby/2.7.0/gems/brwiki-0.0.2/lib/brwiki.rb:1:in `require': cannot load such file -- httparty (LoadError)
\tfrom /app/vendor/bundle/ruby/2.7.0/gems/brwiki-0.0.2/lib/brwiki.rb:1:in `'
```
httparty is not defined as a dependency.

**Comment by Luizin5** [comment]
Try downloading the gem again.
I just put a new version with this bug fixed

**Comment by mensfeld** [comment]
Works. Thank you!
